apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 383085609393.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 383085609393.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 77e09e50
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
